export default [
  {
    title: '网站通用图标',
    icons: [
      { code: 'alarm', text: '', tag: 'new' },
      { code: 'train', text: '', tag: 'new' },
      { code: 'toll', text: '', tag: 'new' },
      { code: 'smart-glass', text: '', tag: 'new' },
      { code: 'police-car', text: '', tag: 'new' },
      { code: 'relationship', text: '', tag: 'new' },
      { code: 'wifi-rotate45', text: '', tag: 'new' },
      { code: 'perception', text: '', tag: 'new' },
      { code: 'cellphone', text: '', tag: 'new' },
      { code: 'no-img', text: '', tag: 'new' },
      { code: 'perception-basement', text: '', tag: 'new' },
      { code: 'panoramic-camera', text: '', tag: 'new' },
      { code: 'in-conversation', text: '', tag: 'new' },
      { code: 'hotel', text: '', tag: 'new' },
      { code: 'internet-cafe', text: '', tag: 'new' },
      { code: 'feedback', text: '', tag: 'new' },
      { code: 'airport', text: '', tag: 'new' },
      { code: 'scan-exit', text: '' },
      { code: 'scan-open', text: '' },
      { code: 'smart-search', text: '' },
      { code: 'precise-search', text: '' },
      { code: 'high-search', text: '' },
      { code: 'map', text: '' },
      { code: 'approval', text: '' },
      { code: 'sun-o', text: '' },
      { code: 'moon-o', text: '' },
      { code: 'layers-simple-line', text: '' },
      { code: 'move', text: '' },
    ],
  },
  {
    title: '形状图标',
    icons: [
      { code: 'pack-up', text: '', tag: 'new' },
      { code: 'pack-down', text: '', tag: 'new' },
      { code: 'triangle-o', text: '' },
      { code: 'square-o', text: '' },
      { code: 'circle-o', text: '' },
      { code: 'shape-polygon-add', text: '' },
    ],
  },
  {
    title: '警务中台图标',
    icons: [
      { code: 'location-reback', text: '' },
      { code: 'nodetial', text: '' },
      { code: 'empty-box', text: '' },
      { code: 'uav', text: '' },
      { code: 'gun', text: '' },
      { code: 'lawshot', text: '' },
      { code: 'monitor', text: '' },
      { code: 'vioce', text: '' },
      { code: 'voice-message', text: '' },
      { code: 'switch', text: '' },
      { code: 'shot', text: '' },
      { code: 'speed-transverse', text: '' },
      { code: 'send-o', text: '' },
      { code: 'speed-portrait', text: '' },
      { code: 'send', text: '' },
      { code: 'recover', text: '', tag: 'removed' },
      { code: 'police', text: '' },
      { code: 'person', text: '' },
      { code: 'open-voice', text: '' },
      { code: 'phone-reverse', text: '' },
      { code: 'mute', text: '' },
      { code: 'location', text: '' },
      { code: 'male', text: '' },
      { code: 'location-person', text: '' },
      { code: 'balloon', text: '', tag: 'removed' },
      { code: 'height', text: '' },
      { code: 'full-screen', text: '' },
      { code: 'female', text: '' },
      { code: 'call', text: '' },
      { code: 'close-voice', text: '' },
      { code: 'angle', text: '' },
      { code: 'heatmap', text: '' },
      { code: 'cut-picture', text: '' },
      { code: 'dimension', text: '' },
      { code: 'compare', text: '' },
      { code: 'trend', text: '' },
    ],
  },
  {
    title: 'ant-方向性图标',
    icons: [
      { code: 'step-backward', text: '' },
      { code: 'step-forward', text: '' },
      { code: 'fast-backward', text: '' },
      { code: 'fast-forward', text: '' },
      { code: 'shrink', text: '' },
      { code: 'arrows-alt', text: '' },
      { code: 'down', text: '' },
      { code: 'up', text: '' },
      { code: 'left', text: '' },
      { code: 'right', text: '' },
      { code: 'caret-up', text: '' },
      { code: 'caret-down', text: '' },
      { code: 'caret-left', text: '' },
      { code: 'caret-right', text: '' },
      { code: 'up-circle', text: '' },
      { code: 'down-circle', text: '' },
      { code: 'left-circle', text: '' },
      { code: 'right-circle', text: '' },
      { code: 'up-circle-o', text: '' },
      { code: 'down-circle-o', text: '' },
      { code: 'right-circle-o', text: '' },
      { code: 'left-circle-o', text: '' },
      { code: 'double-right', text: '' },
      { code: 'double-left', text: '' },
      { code: 'verticle-left', text: '' },
      { code: 'verticle-right', text: '' },
      { code: 'forward', text: '' },
      { code: 'backward', text: '' },
      { code: 'rollback', text: '' },
      { code: 'enter', text: '' },
      { code: 'retweet', text: '' },
      { code: 'swap', text: '' },
      { code: 'swap-left', text: '' },
      { code: 'swap-right', text: '' },
      { code: 'arrow-up', text: '' },
      { code: 'arrow-down', text: '' },
      { code: 'arrow-left', text: '' },
      { code: 'arrow-right', text: '' },
      { code: 'play-circle', text: '' },
      { code: 'play-circle-o', text: '' },
      { code: 'up-square', text: '' },
      { code: 'down-square', text: '' },
      { code: 'left-square', text: '' },
      { code: 'right-square', text: '' },
      { code: 'up-square-o', text: '' },
      { code: 'down-square-o', text: '' },
      { code: 'left-square-o', text: '' },
      { code: 'right-square-o', text: '' },
      { code: 'login', text: '' },
      { code: 'logout', text: '' },
      { code: 'menu-fold', text: '' },
      { code: 'menu-unfold', text: '' },
    ],
  },
  {
    title: 'ant-提示建议性图标',
    icons: [
      { code: 'question', text: '' },
      { code: 'question-circle-o', text: '' },
      { code: 'question-circle', text: '' },
      { code: 'plus', text: '' },
      { code: 'plus-circle-o', text: '' },
      { code: 'plus-circle', text: '' },
      { code: 'pause', text: '' },
      { code: 'pause-circle-o', text: '' },
      { code: 'pause-circle', text: '' },
      { code: 'minus', text: '' },
      { code: 'minus-circle-o', text: '' },
      { code: 'minus-circle', text: '' },
      { code: 'plus-square', text: '' },
      { code: 'plus-square-o', text: '' },
      { code: 'minus-square', text: '' },
      { code: 'minus-square-o', text: '' },
      { code: 'info', text: '' },
      { code: 'info-circle-o', text: '' },
      { code: 'info-circle', text: '' },
      { code: 'exclamation', text: '' },
      { code: 'exclamation-circle-o', text: '' },
      { code: 'exclamation-circle', text: '' },
      { code: 'close', text: '' },
      { code: 'close-circle', text: '' },
      { code: 'close-circle-o', text: '' },
      { code: 'close-square', text: '' },
      { code: 'close-square-o', text: '' },
      { code: 'check', text: '' },
      { code: 'check-circle', text: '' },
      { code: 'check-circle-o', text: '' },
      { code: 'check-square', text: '' },
      { code: 'check-square-o', text: '' },
      { code: 'clock-circle-o', text: '' },
      { code: 'clock-circle', text: '' },
      { code: 'warning', text: '' },
    ],
  },
  {
    title: 'ant-网站通用图标',
    icons: [
      { code: 'lock', text: '' },
      { code: 'unlock', text: '' },
      { code: 'area-chart', text: '' },
      { code: 'pie-chart', text: '' },
      { code: 'bar-chart', text: '' },
      { code: 'dot-chart', text: '' },
      { code: 'bars', text: '' },
      { code: 'book', text: '' },
      { code: 'calendar', text: '' },
      { code: 'cloud', text: '' },
      { code: 'cloud-download', text: '' },
      { code: 'code', text: '' },
      { code: 'code-o', text: '' },
      { code: 'copy', text: '' },
      { code: 'credit-card', text: '' },
      { code: 'delete', text: '' },
      { code: 'desktop', text: '' },
      { code: 'download', text: '' },
      { code: 'edit', text: '' },
      { code: 'ellipsis', text: '' },
      { code: 'file', text: '' },
      { code: 'file-text', text: '' },
      { code: 'file-unknown', text: '' },
      { code: 'file-pdf', text: '' },
      { code: 'file-word', text: '' },
      { code: 'file-excel', text: '' },
      { code: 'file-jpg', text: '' },
      { code: 'file-ppt', text: '' },
      { code: 'file-add', text: '' },
      { code: 'folder', text: '' },
      { code: 'folder-open', text: '' },
      { code: 'folder-add', text: '' },
      { code: 'hdd', text: '' },
      { code: 'frown', text: '' },
      { code: 'frown-o', text: '' },
      { code: 'meh', text: '' },
      { code: 'meh-o', text: '' },
      { code: 'smile', text: '' },
      { code: 'smile-o', text: '' },
      { code: 'inbox', text: '' },
      { code: 'laptop', text: '' },
      { code: 'appstore-o', text: '' },
      { code: 'appstore', text: '' },
      { code: 'line-chart', text: '' },
      { code: 'link', text: '' },
      { code: 'mail', text: '' },
      { code: 'mobile', text: '' },
      { code: 'notification', text: '' },
      { code: 'paper-clip', text: '' },
      { code: 'picture', text: '' },
      { code: 'poweroff', text: '' },
      { code: 'reload', text: '' },
      { code: 'search', text: '' },
      { code: 'setting', text: '' },
      { code: 'share-alt', text: '' },
      { code: 'shopping-cart', text: '' },
      { code: 'tablet', text: '' },
      { code: 'tag', text: '' },
      { code: 'tag-o', text: '' },
      { code: 'tags', text: '' },
      { code: 'tags-o', text: '' },
      { code: 'to-top', text: '' },
      { code: 'upload', text: '' },
      { code: 'user', text: '' },
      { code: 'video-camera', text: '' },
      { code: 'home', text: '' },
      { code: 'loading', text: '' },
      { code: 'loading-3-quarters', text: '' },
      { code: 'cloud-upload-o', text: '' },
      { code: 'cloud-download-o', text: '' },
      { code: 'cloud-upload', text: '' },
      { code: 'cloud-o', text: '' },
      { code: 'star-o', text: '' },
      { code: 'star', text: '' },
      { code: 'heart-o', text: '' },
      { code: 'heart', text: '' },
      { code: 'environment', text: '' },
      { code: 'environment-o', text: '' },
      { code: 'eye', text: '' },
      { code: 'eye-o', text: '' },
      { code: 'camera', text: '' },
      { code: 'camera-o', text: '' },
      { code: 'save', text: '' },
      { code: 'team', text: '' },
      { code: 'solution', text: '' },
      { code: 'phone', text: '' },
      { code: 'filter', text: '' },
      { code: 'exception', text: '' },
      { code: 'export', text: '' },
      { code: 'customer-service', text: '' },
      { code: 'qrcode', text: '' },
      { code: 'scan', text: '' },
      { code: 'like', text: '' },
      { code: 'like-o', text: '' },
      { code: 'dislike', text: '' },
      { code: 'dislike-o', text: '' },
      { code: 'message', text: '' },
      { code: 'pay-circle', text: '' },
      { code: 'pay-circle-o', text: '' },
      { code: 'calculator', text: '' },
      { code: 'pushpin', text: '' },
      { code: 'pushpin-o', text: '' },
      { code: 'bulb', text: '' },
      { code: 'select', text: '' },
      { code: 'switcher', text: '' },
      { code: 'rocket', text: '' },
      { code: 'bell', text: '' },
      { code: 'disconnect', text: '' },
      { code: 'database', text: '' },
      { code: 'compass', text: '' },
      { code: 'barcode', text: '' },
      { code: 'hourglass', text: '' },
      { code: 'key', text: '' },
      { code: 'flag', text: '' },
      { code: 'layout', text: '' },
      { code: 'printer', text: '' },
      { code: 'sound', text: '' },
      { code: 'usb', text: '' },
      { code: 'skin', text: '' },
      { code: 'tool', text: '' },
      { code: 'sync', text: '' },
      { code: 'wifi', text: '' },
      { code: 'car', text: '' },
      { code: 'schedule', text: '' },
      { code: 'user-add', text: '' },
      { code: 'user-delete', text: '' },
      { code: 'usergroup-add', text: '' },
      { code: 'usergroup-delete', text: '' },
      { code: 'man', text: '' },
      { code: 'woman', text: '' },
      { code: 'shop', text: '' },
      { code: 'gift', text: '' },
      { code: 'idcard', text: '' },
      { code: 'medicine-box', text: '' },
      { code: 'red-envelope', text: '' },
      { code: 'coffee', text: '' },
      { code: 'copyright', text: '' },
      { code: 'trademark', text: '' },
      { code: 'safety', text: '' },
      { code: 'wallet', text: '' },
      { code: 'bank', text: '' },
      { code: 'trophy', text: '' },
      { code: 'contacts', text: '' },
      { code: 'global', text: '' },
      { code: 'shake', text: '' },
      { code: 'api', text: '' },
      { code: 'fork', text: '' },
      { code: 'dashboard', text: '' },
      { code: 'form', text: '' },
      { code: 'table', text: '' },
      { code: 'profile', text: '' },
    ],
  },
];
