/* 这里是因为宽高不规范而不推荐使用的图标 */
export const deprecated = ["all-1", "disputes-circle", "bicycle", "cpu", "video-speed", "personnel-data", "mediation-power", "all", "prove", "job", "take-photo", "img", "loopline", "warning-o", "revoke-o", "toll", "switch", "shot", "smart-glass", "perception", "no-img", "panoramic-camera", "pack-up", "pack-down", "monitor", "gun", "feedback", "empty-box", "vioce", "speed-portrait", "send", "mute", "location", "location-person", "height", "full-screen", "cut-picture", "move", "heart", "heart-o", "backward"];

export default [
  {
    title: "未分类",
    icons: [
      { code: "parallel", text: "", tag: "new" },
      { code: "swm-pool", text: "", tag: "new" },
      { code: "manual", text: "", tag: "new" },
      { code: "swm-lane", text: "", tag: "new" },
      { code: "exclusive", text: "", tag: "new" },
      { code: "contain", text: "", tag: "new" },
      { code: "adjuster", text: "", tag: "new" },
      { code: "order-state-finished", text: "", tag: "new" },
      { code: "order-state-pending", text: "", tag: "new" },
      { code: "font-format", text: "", tag: "new" },
      { code: "image-upload-tips", text: "" },
      { code: "video-o", text: "" },
      { code: "equipment-o", text: "" },
      { code: "data-source-polygon", text: "" },
      { code: "audio-o", text: "" },
      { code: "ga", text: "" },
      { code: "api-logo", text: "" },
      { code: "monitor-o", text: "" },
      { code: "get-back", text: "" },
      { code: "scope", text: "" },
      { code: "status", text: "" },
      { code: "relation-o", text: "" },
      { code: "video", text: "" },
      { code: "police-strength", text: "" },
      { code: "take-photo-o", text: "" },
      { code: "hotel-map", text: "" },
      { code: "feedback-rec", text: "" },
      { code: "id-card-o", text: "" },
      { code: "iot", text: "" },
      { code: "mac-icon", text: "" },
      { code: "horn", text: "" },
      { code: "avatar-default-circle", text: "" },
      { code: "cellphone-mac", text: "" },
      { code: "simcard", text: "" },
      { code: "cellphone-imsi", text: "" },
      { code: "qq-icon", text: "" },
      { code: "avatar-circle", text: "" },
      { code: "cancel-square-o", text: "" },
      { code: "setting-circle-o", text: "" },
      { code: "setting-o", text: "" },
      { code: "scope-setting-o", text: "" },
      { code: "database-setting-o", text: "" },
      { code: "picture-1", text: "" },
      { code: "task-o", text: "" },
      { code: "target-o", text: "" },
      { code: "identity-o", text: "", tag: "resize" },
      { code: "order-o", text: "" },
      { code: "engine-o", text: "" },
      { code: "id-circle", text: "" },
      { code: "rfid", text: "" },
      { code: "gate-brake", text: "" },
      { code: "download-video", text: "" },
      { code: "sim-card", text: "" },
      { code: "batch-import", text: "" },
      { code: "police-portrait", text: "" },
      { code: "shield-security", text: "" },
      { code: "others-camera", text: "" },
      { code: "face", text: "" },
      { code: "out-door", text: "" },
      { code: "stop-video", text: "" },
      { code: "save-video", text: "" },
      { code: "track-curve", text: "" },
      { code: "track-straight", text: "" },
      { code: "delete-o", text: "" },
      { code: "alipay-circle", text: "" },
      { code: "weibo-circle", text: "" },
      { code: "wechat-circle", text: "" },
      { code: "voice", text: "" },
      { code: "video-circle", text: "" },
      { code: "time-circle-o", text: "" },
      { code: "picture", text: "" },
      { code: "text", text: "" },
      { code: "passport", text: "" },
      { code: "more-circle-o", text: "" },
      { code: "imei", text: "" },
      { code: "identity-card", text: "" },
      { code: "mac", text: "" },
      { code: "hourglass-1", text: "" },
      { code: "edit-o", text: "" },
      { code: "console-circle-o", text: "" },
      { code: "developer", text: "" },
      { code: "capability-o", text: "" },
      { code: "bankcard-rectangle", text: "" },
      { code: "map-china", text: "" },
      { code: "plug", text: "" },
    ],
  },
  {
    title: "logo",
    icons: [
      { code: "taoan", text: "" },
    ],
  },
  {
    title: "taoan",
    icons: [
      { code: "mail-circle", text: "" },
      { code: "multiplayer-o", text: "" },
      { code: "install-o", text: "" },
      { code: "store-o", text: "" },
      { code: "computer-desktop-o", text: "" },
      { code: "computer-chart-o", text: "" },
      { code: "flag-circle", text: "" },
      { code: "prompt-circle", text: "" },
      { code: "alarm-circle", text: "" },
      { code: "order-number-circle", text: "" },
      { code: "renovate", text: "" },
      { code: "pitch-on", text: "" },
      { code: "rise", text: "" },
      { code: "decline", text: "" },
      { code: "remind-circle", text: "" },
      { code: "order-rectangular", text: "" },
      { code: "market-p", text: "" },
      { code: "market-y", text: "" },
      { code: "user-manage-b", text: "" },
      { code: "advert-b", text: "" },
      { code: "order-b", text: "" },
      { code: "bill-b", text: "" },
      { code: "add-b", text: "" },
      { code: "service-o", text: "" },
      { code: "safety-o", text: "" },
      { code: "region-o", text: "" },
      { code: "order-list", text: "" },
      { code: "finance-o", text: "" },
    ],
  },
  {
    title: "网站通用图标",
    icons: [
      { code: "gateway", text: "" },
      { code: "pennant", text: "" },
      { code: "compass-solid", text: "" },
      { code: "narrow", text: "" },
      { code: "extend", text: "" },
      { code: "gun-camera", text: "" },
      { code: "live-video", text: "" },
      { code: "playback-video", text: "" },
      { code: "indoor-map", text: "" },
      { code: "face-recognition", text: "" },
      { code: "all-1", text: "" },
      { code: "industry-circle", text: "" },
      { code: "security-circle", text: "" },
      { code: "disputes-circle", text: "" },
      { code: "traffic", text: "" },
      { code: "location-point-gray", text: "" },
      { code: "bicycle", text: "" },
      { code: "motorcycle", text: "" },
      { code: "walking", text: "" },
      { code: "eyes-open", text: "" },
      { code: "eyes-hide", text: "" },
      { code: "cpu", text: "" },
      { code: "ssd", text: "" },
      { code: "pointer-move", text: "" },
      { code: "screenshot", text: "" },
      { code: "zoom-in", text: "" },
      { code: "zoom-out", text: "" },
      { code: "message-bell", text: "" },
      { code: "gesture", text: "" },
      { code: "discern", text: "" },
      { code: "cb-logo", text: "" },
      { code: "video-speed", text: "" },
      { code: "gun-rotate", text: "" },
      { code: "video-command", text: "" },
      { code: "head-analysis", text: "" },
      { code: "total-records", text: "" },
      { code: "total-pillars", text: "" },
      { code: "trend-chart", text: "" },
      { code: "increase-circle", text: "" },
      { code: "personnel-data", text: "" },
      { code: "mediation-power", text: "" },
      { code: "all", text: "" },
      { code: "prove", text: "" },
      { code: "job", text: "" },
      { code: "tick", text: "" },
      { code: "help", text: "" },
      { code: "hammer", text: "" },
      { code: "dna", text: "" },
      { code: "fingerprint", text: "" },
      { code: "plus-bold", text: "" },
      { code: "judicial-circle-hover", text: "" },
      { code: "judicial-circle", text: "" },
      { code: "ellipse-vertical", text: "" },
      { code: "location-blue", text: "" },
      { code: "gun-bubble-blue", text: "" },
      { code: "gun-bubble-white", text: "" },
      { code: "gun-bubble-black", text: "" },
      { code: "grid-8", text: "" },
      { code: "3d", text: "" },
      { code: "grid-5", text: "" },
      { code: "2d", text: "" },
      { code: "tie", text: "" },
      { code: "star-customer", text: "" },
      { code: "map-simple", text: "" },
      { code: "location-point-solid", text: "" },
      { code: "take-photo", text: "" },
      { code: "img", text: "" },
      { code: "voice-call", text: "" },
      { code: "cancel-call", text: "" },
      { code: "file-text-o", text: "" },
      { code: "record", text: "" },
      { code: "visiblerange", text: "" },
      { code: "sticking-point", text: "" },
      { code: "loopline", text: "" },
      { code: "location-focus", text: "" },
      { code: "street", text: "" },
      { code: "building", text: "" },
      { code: "world", text: "" },
      { code: "room", text: "" },
      { code: "thing", text: "" },
      { code: "human", text: "" },
      { code: "card", text: "" },
      { code: "relation", text: "" },
      { code: "profile-1", text: "" },
      { code: "judicial", text: "" },
      { code: "warning-o", text: "" },
      { code: "call-close", text: "" },
      { code: "revoke-o", text: "" },
      { code: "police-avatar", text: "" },
      { code: "track-point-blue", text: "" },
      { code: "camera-point-small", text: "" },
      { code: "track-point-red", text: "" },
      { code: "location-point-blue", text: "" },
      { code: "location-point-red", text: "" },
      { code: "alarm", text: "" },
      { code: "train", text: "" },
      { code: "toll", text: "" },
      { code: "smart-glass", text: "" },
      { code: "police-car", text: "" },
      { code: "relationship", text: "" },
      { code: "wifi-rotate45", text: "" },
      { code: "perception", text: "" },
      { code: "cellphone", text: "" },
      { code: "no-img", text: "" },
      { code: "perception-basement", text: "" },
      { code: "panoramic-camera", text: "" },
      { code: "in-conversation", text: "" },
      { code: "hotel", text: "" },
      { code: "internet-cafe", text: "" },
      { code: "feedback", text: "" },
      { code: "airport", text: "" },
      { code: "scan-exit", text: "" },
      { code: "scan-open", text: "" },
      { code: "smart-search", text: "" },
      { code: "precise-search", text: "" },
      { code: "high-search", text: "" },
      { code: "map", text: "" },
      { code: "approval", text: "" },
      { code: "sun-o", text: "" },
      { code: "moon-o", text: "" },
      { code: "layers-simple-line", text: "" },
      { code: "move", text: "" },
    ],
  },
  {
    title: "地图标记物",
    icons: [
      { code: "international-relation", text: "" },
      { code: "train-station", text: "" },
      { code: "religion", text: "" },
      { code: "port", text: "" },
      { code: "venue", text: "" },
      { code: "warehouse", text: "" },
      { code: "special-industry", text: "" },
      { code: "traffic-facilities", text: "" },
      { code: "ticket-office", text: "" },
      { code: "shopping-mall", text: "" },
      { code: "shooting-range", text: "" },
      { code: "post-office", text: "" },
      { code: "school", text: "" },
      { code: "scenic-spot", text: "" },
      { code: "procuratorate", text: "" },
      { code: "muslim", text: "" },
      { code: "park", text: "" },
      { code: "logistics", text: "" },
      { code: "organization", text: "" },
      { code: "news", text: "" },
      { code: "fire-hydrant", text: "" },
      { code: "hospital", text: "" },
      { code: "gas-station", text: "" },
      { code: "entertainment", text: "" },
      { code: "checkpoint", text: "" },
      { code: "atm", text: "" },
      { code: "bank-solid", text: "" },
      { code: "bus-stop", text: "" },
      { code: "carpark", text: "" },
      { code: "accommodation", text: "" },
      { code: "keyboard", text: "" },
    ],
  },
  {
    title: "形状图标",
    icons: [
      { code: "polygon", text: "" },
      { code: "pack-up", text: "" },
      { code: "pack-down", text: "" },
      { code: "triangle-o", text: "" },
      { code: "square-o", text: "" },
      { code: "circle-o", text: "" },
      { code: "shape-polygon-add", text: "" },
    ],
  },
  {
    title: "特定图标",
    icons: [
      { code: "location-reback", text: "" },
      { code: "nodetial", text: "" },
      { code: "empty-box", text: "" },
      { code: "uav", text: "" },
      { code: "gun", text: "" },
      { code: "lawshot", text: "" },
      { code: "monitor", text: "" },
      { code: "vioce", text: "" },
      { code: "voice-message", text: "" },
      { code: "switch", text: "" },
      { code: "shot", text: "" },
      { code: "speed-transverse", text: "" },
      { code: "send-o", text: "" },
      { code: "speed-portrait", text: "" },
      { code: "send", text: "" },
      { code: "police", text: "" },
      { code: "person", text: "" },
      { code: "open-voice", text: "" },
      { code: "phone-reverse", text: "" },
      { code: "mute", text: "" },
      { code: "location", text: "" },
      { code: "male", text: "" },
      { code: "location-person", text: "" },
      { code: "height", text: "" },
      { code: "full-screen", text: "" },
      { code: "female", text: "" },
      { code: "call", text: "" },
      { code: "close-voice", text: "" },
      { code: "angle", text: "" },
      { code: "heatmap", text: "" },
      { code: "cut-picture", text: "" },
      { code: "dimension", text: "" },
      { code: "compare", text: "" },
      { code: "trend", text: "" },
    ],
  },
  {
    title: "ant-方向性图标",
    icons: [
      { code: "step-backward", text: "" },
      { code: "step-forward", text: "" },
      { code: "fast-backward", text: "" },
      { code: "fast-forward", text: "" },
      { code: "shrink", text: "" },
      { code: "arrows-alt", text: "" },
      { code: "down", text: "" },
      { code: "up", text: "" },
      { code: "left", text: "" },
      { code: "right", text: "" },
      { code: "caret-up", text: "" },
      { code: "caret-down", text: "" },
      { code: "caret-left", text: "" },
      { code: "caret-right", text: "" },
      { code: "up-circle", text: "" },
      { code: "down-circle", text: "" },
      { code: "left-circle", text: "" },
      { code: "right-circle", text: "" },
      { code: "up-circle-o", text: "" },
      { code: "down-circle-o", text: "" },
      { code: "right-circle-o", text: "" },
      { code: "left-circle-o", text: "" },
      { code: "double-right", text: "" },
      { code: "double-left", text: "" },
      { code: "verticle-left", text: "" },
      { code: "verticle-right", text: "" },
      { code: "forward", text: "" },
      { code: "backward", text: "" },
      { code: "rollback", text: "" },
      { code: "enter", text: "" },
      { code: "retweet", text: "" },
      { code: "swap", text: "" },
      { code: "swap-left", text: "" },
      { code: "swap-right", text: "" },
      { code: "arrow-up", text: "" },
      { code: "arrow-down", text: "" },
      { code: "arrow-left", text: "" },
      { code: "arrow-right", text: "" },
      { code: "play-circle", text: "" },
      { code: "play-circle-o", text: "" },
      { code: "up-square", text: "" },
      { code: "down-square", text: "" },
      { code: "left-square", text: "" },
      { code: "right-square", text: "" },
      { code: "up-square-o", text: "" },
      { code: "down-square-o", text: "" },
      { code: "left-square-o", text: "" },
      { code: "right-square-o", text: "" },
      { code: "login", text: "" },
      { code: "logout", text: "" },
      { code: "menu-fold", text: "" },
      { code: "menu-unfold", text: "" },
    ],
  },
  {
    title: "ant-提示建议性图标",
    icons: [
      { code: "question", text: "" },
      { code: "question-circle-o", text: "" },
      { code: "question-circle", text: "" },
      { code: "plus", text: "" },
      { code: "plus-circle-o", text: "" },
      { code: "plus-circle", text: "" },
      { code: "pause", text: "" },
      { code: "pause-circle-o", text: "" },
      { code: "pause-circle", text: "" },
      { code: "minus", text: "" },
      { code: "minus-circle-o", text: "" },
      { code: "minus-circle", text: "" },
      { code: "plus-square", text: "" },
      { code: "plus-square-o", text: "" },
      { code: "minus-square", text: "" },
      { code: "minus-square-o", text: "" },
      { code: "info", text: "" },
      { code: "info-circle-o", text: "" },
      { code: "info-circle", text: "" },
      { code: "exclamation", text: "" },
      { code: "exclamation-circle-o", text: "" },
      { code: "exclamation-circle", text: "" },
      { code: "close", text: "" },
      { code: "close-circle", text: "" },
      { code: "close-circle-o", text: "" },
      { code: "close-square", text: "" },
      { code: "close-square-o", text: "" },
      { code: "check", text: "" },
      { code: "check-circle", text: "" },
      { code: "check-circle-o", text: "" },
      { code: "check-square", text: "" },
      { code: "check-square-o", text: "" },
      { code: "clock-circle-o", text: "" },
      { code: "clock-circle", text: "" },
      { code: "warning", text: "" },
    ],
  },
  {
    title: "ant-网站通用图标",
    icons: [
      { code: "lock", text: "" },
      { code: "unlock", text: "" },
      { code: "area-chart", text: "" },
      { code: "pie-chart", text: "" },
      { code: "bar-chart", text: "" },
      { code: "dot-chart", text: "" },
      { code: "bars", text: "" },
      { code: "book", text: "" },
      { code: "calendar", text: "" },
      { code: "cloud", text: "" },
      { code: "cloud-download", text: "" },
      { code: "code", text: "" },
      { code: "code-o", text: "" },
      { code: "copy", text: "" },
      { code: "credit-card", text: "" },
      { code: "delete", text: "" },
      { code: "desktop", text: "" },
      { code: "download", text: "" },
      { code: "edit", text: "" },
      { code: "ellipsis", text: "" },
      { code: "file", text: "" },
      { code: "file-text", text: "" },
      { code: "file-unknown", text: "" },
      { code: "file-pdf", text: "" },
      { code: "file-word", text: "" },
      { code: "file-excel", text: "" },
      { code: "file-jpg", text: "" },
      { code: "file-ppt", text: "" },
      { code: "file-add", text: "" },
      { code: "folder", text: "" },
      { code: "folder-open", text: "" },
      { code: "folder-add", text: "" },
      { code: "hdd", text: "" },
      { code: "frown", text: "" },
      { code: "frown-o", text: "" },
      { code: "meh", text: "" },
      { code: "meh-o", text: "" },
      { code: "smile", text: "" },
      { code: "smile-o", text: "" },
      { code: "inbox", text: "" },
      { code: "laptop", text: "" },
      { code: "appstore-o", text: "" },
      { code: "appstore", text: "" },
      { code: "line-chart", text: "" },
      { code: "link", text: "" },
      { code: "mail", text: "" },
      { code: "mobile", text: "" },
      { code: "notification", text: "" },
      { code: "paper-clip", text: "" },
      { code: "picture", text: "" },
      { code: "poweroff", text: "" },
      { code: "reload", text: "" },
      { code: "search", text: "" },
      { code: "setting", text: "" },
      { code: "share-alt", text: "" },
      { code: "shopping-cart", text: "" },
      { code: "tablet", text: "" },
      { code: "tag", text: "" },
      { code: "tag-o", text: "" },
      { code: "tags", text: "" },
      { code: "tags-o", text: "" },
      { code: "to-top", text: "" },
      { code: "upload", text: "" },
      { code: "user", text: "" },
      { code: "video-camera", text: "" },
      { code: "home", text: "" },
      { code: "loading", text: "" },
      { code: "loading-3-quarters", text: "" },
      { code: "cloud-upload-o", text: "" },
      { code: "cloud-download-o", text: "" },
      { code: "cloud-upload", text: "" },
      { code: "cloud-o", text: "" },
      { code: "star-o", text: "" },
      { code: "star", text: "" },
      { code: "heart-o", text: "" },
      { code: "heart", text: "" },
      { code: "environment", text: "" },
      { code: "environment-o", text: "" },
      { code: "eye", text: "" },
      { code: "eye-o", text: "" },
      { code: "camera", text: "" },
      { code: "camera-o", text: "" },
      { code: "save", text: "" },
      { code: "team", text: "" },
      { code: "solution", text: "" },
      { code: "phone", text: "" },
      { code: "filter", text: "" },
      { code: "exception", text: "" },
      { code: "export", text: "" },
      { code: "customer-service", text: "" },
      { code: "qrcode", text: "" },
      { code: "scan", text: "" },
      { code: "like", text: "" },
      { code: "like-o", text: "" },
      { code: "dislike", text: "" },
      { code: "dislike-o", text: "" },
      { code: "message", text: "" },
      { code: "pay-circle", text: "" },
      { code: "pay-circle-o", text: "" },
      { code: "calculator", text: "" },
      { code: "pushpin", text: "" },
      { code: "pushpin-o", text: "" },
      { code: "bulb", text: "" },
      { code: "select", text: "" },
      { code: "switcher", text: "" },
      { code: "rocket", text: "" },
      { code: "bell", text: "" },
      { code: "disconnect", text: "" },
      { code: "database", text: "" },
      { code: "compass", text: "" },
      { code: "barcode", text: "" },
      { code: "hourglass", text: "" },
      { code: "key", text: "" },
      { code: "flag", text: "" },
      { code: "layout", text: "" },
      { code: "printer", text: "" },
      { code: "sound", text: "" },
      { code: "usb", text: "" },
      { code: "skin", text: "" },
      { code: "tool", text: "" },
      { code: "sync", text: "" },
      { code: "wifi", text: "" },
      { code: "car", text: "" },
      { code: "schedule", text: "" },
      { code: "user-add", text: "" },
      { code: "user-delete", text: "" },
      { code: "usergroup-add", text: "" },
      { code: "usergroup-delete", text: "" },
      { code: "man", text: "" },
      { code: "woman", text: "" },
      { code: "shop", text: "" },
      { code: "gift", text: "" },
      { code: "idcard", text: "" },
      { code: "medicine-box", text: "" },
      { code: "red-envelope", text: "" },
      { code: "coffee", text: "" },
      { code: "copyright", text: "" },
      { code: "trademark", text: "" },
      { code: "safety", text: "" },
      { code: "wallet", text: "" },
      { code: "bank", text: "" },
      { code: "trophy", text: "" },
      { code: "contacts", text: "" },
      { code: "global", text: "" },
      { code: "shake", text: "" },
      { code: "api", text: "" },
      { code: "fork", text: "" },
      { code: "dashboard", text: "" },
      { code: "form", text: "" },
      { code: "table", text: "" },
      { code: "profile", text: "" },
    ],
  },
];
