export default {
  "delete-circle-o": "delete-o",
  "voice-circle": "voice",
  "picture-circle": "picture",
  "text-circle": "text",
  "passport-circle": "passport",
  "imei-circle": "imei",
  "identity-card-circle": "identity-card",
  "mac-address-circle": "mac",
  "hourglass-circle": "hourglass-1",
  "edit-circle-o": "edit-o",
  "developer-circle-": "developer",
  "capability-circles-o": "capability-o",
  "bankcard-circle": "bankcard-rectangle",
};
