/* 下列图标支持svg模式 */
module.exports = [
  "police-avatar",
  "in-conversation",
  "airport",
  "hotel",
  "track-point-blue",
  "camera-point-samll",
  "track-point-red",
  "location-point-blue",
  "location-point-red",
  "judicial-circle-hover",
  "judicial-circle",
  "location-blue",
  "gun-bubble-blue",
  "gun-bubble-white",
  "gun-bubble-black",
  "market-p",
  "market-y",
  "police-portrait",
  "avatar-circle",
  "avatar-default-circle",
];
